handlers:
  -
    # Status handler - custom type
    type: status
    # Restrict to a specific server. Absent means on all servers
    #restrict:
    #  - h2
    method: get
    pattern:
      - /status
  -
    type: reject
    method: get
    pattern:
      - /test
  

databases:
  test:
    host: 172.17.0.2
    port: 5432
    database: postgres
    user: postgres
    password: password
    ssl: false
